### ISSUE TITLE
Shard autoconnect isn't retrying after disconnect or failure

### ISSUE THREAD

**Issue by PulsePanda** [PulsePanda/Crystal#22]

**Comment by PulsePanda** [comment]
Correction, will not reconnect after not being able to connect the first time

**Comment by PulsePanda** [comment]
this is the Shard's log:
VERSION: 0.1.1
###############CHS Shard###############
System logging enabled
Loading configuration file...
Please initialize the Config with Nerv before proceeding!
KRIPT: Kript keys created and ready to be used.
Initializing client...
Initializing Patcher...
Getting version from Heart.
Unable to connect to server. Check your network connection and try again. Closing client.

**Comment by PulsePanda** [comment]
Getting version from Heart.
java.net.ConnectException: Connection refused: connect
	at java.net.DualStackPlainSocketImpl.connect0(Native Method)
	at java.net.DualStackPlainSocketImpl.socketConnect(DualStackPlainSocketImpl.java:79)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
	at java.net.PlainSocketImpl.connect(PlainSocketImpl.java:172)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at java.net.Socket.connect(Socket.java:538)
	at java.net.Socket.<init>(Socket.java:434)
	at java.net.Socket.<init>(Socket.java:211)
	at Netta.Connection.Client.ClientTemplate.run(ClientTemplate.java:68)
	at java.lang.Thread.run(Thread.java:745)
Unable to connect to server. Check your network connection and try again. Closing client.

**Comment by PulsePanda** [comment]
Additional info: If the shard is connected, and the heart terminates but stay's open the shard will reconnect. if the shard is connected, and the heart is terminated and closed, the shard will fail to connect but keep trying like it should. However, if the heart is not open, and the shard starts and tries to connect, it will fail and stop trying.

**Comment by PulsePanda** [comment]
Further info: When the shardconnectionthread is running, `sc.StartShardClient()` is exiting the application. The thread does NOT keep running
